- type: replace
  path: /releases/-
  value:
    name: bosh-docker-cpi
    sha1: 075bc0264d2548173da55a40127757ae962a25b1
    url: https://bosh.io/d/github.com/cppforlife/bosh-docker-cpi-release?v=0.0.5
    version: 0.0.5

- type: replace
  path: /releases/name=bosh/version?
  value: create

- type: replace
  path: /stemcells?
  value:
  - alias: default
    os: ubuntu-trusty
    version: latest

- type: replace
  path: /instance_groups/name=bosh/stemcell?
  value: default

- type: remove
  path: /resource_pools

- type: remove
  path: /instance_groups/name=bosh/resource_pool

- type: replace
  path: /instance_groups/name=bosh/vm_type?
  value: default

- type: replace
  path: /instance_groups/name=bosh/azs?
  value: [z1]

- type: remove
  path: /networks

- type: remove
  path: /disk_pools

- type: remove
  path: /instance_groups/name=bosh/persistent_disk_pool

- type: replace
  path: /instance_groups/name=bosh/persistent_disk_type?
  value: default

- type: remove
  path: /instance_groups/name=bosh/jobs/name=health_monitor

- type: replace
  path: /update?
  value:
    canary_watch_time: 60000-300000
    update_watch_time: 60000-300000
    serial: false
    canaries: 1
    max_in_flight: 1

- type: replace
  path: /instance_groups/name=bosh/jobs/-
  value: &cpi_job
    name: docker_cpi
    release: bosh-docker-cpi
    properties:
      docker_cpi:
        docker:
          host: ((docker_host))
          tls: ((docker_tls))
        agent:
          mbus: nats://nats:((nats_password))@((internal_ip)):4222
          blobstore:
            provider: dav
            options:
              endpoint: http://((internal_ip)):25250
              user: agent
              password: ((blobstore_agent_password))

- type: replace
  path: /instance_groups/name=bosh/properties/director/cpi_job?
  value: docker_cpi

- type: replace
  path: /instance_groups/name=bosh/properties/director/local_dns?/enabled?
  value: true

- type: replace
  path: /instance_groups/name=bosh/properties/blobstore/tls?/cert
  value:
    ca: ((blobstore_ca_cert.ca))
    certificate: ((blobstore_ssl.certificate))
    private_key: ((blobstore_ssl.private_key))

- type: replace
  path: /variables/-
  value:
    name: blobstore_ca_cert
    type: certificate
    options:
      is_ca: true
      common_name: bosh-blobstore-ca

- type: replace
  path: /variables/-
  value:
    name: blobstore_ssl
    type: certificate
    options:
      ca: blobstore_ca_cert
      common_name: ((internal_ip))
      alternative_names: [((internal_ip)), 10.254.50.4]

- type: replace
  path: /instance_groups/name=bosh/properties/agent/env?/bosh/blobstores
  value:
    - provider: dav
      options:
        endpoint: 'https://((internal_ip)):25250'
        user: 'agent'
        password: ((blobstore_agent_password))
        tls:
          cert:
            ca: ((blobstore_ca_cert.ca))
