instance_groups:
- instances: 1
  jobs:
  - name: foobar
    properties:
      quote:
        "n": "yes"
        "y": "no"
    release: bosh-release
  name: foobar
  networks:
  - name: a
  stemcell: default
  vm_type: a
name: simple
releases:
- name: bosh-release
  version: 0.1-dev
stemcells:
- alias: default
  name: ubuntu-stemcell
  version: 1
update:
  canaries: 2
  canary_watch_time: 4000
  max_in_flight: 1
  update_watch_time: 20
