---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boshcpi/cpi-certification

inputs:
- name: environment
- name: bosh-src
- name: bosh-cli
- name: bosh-deployment
- name: bosh-release
- name: stemcell
- name: director-state
  optional: true # chain tasks for upgrades

caches:
- path: cache-dot-bosh-dir

params:
  DEPLOY_ARGS: ""
  BAT_INFRASTRUCTURE: ""

outputs:
- name: director-state

run:
  path: bosh-src/ci/bats/tasks/deploy-director.sh
