---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-ruby-go

inputs:
- name: director-state
- name: bosh-src
- name: bosh-cli
- name: stemcell
- name: zookeeper-release

run:
  path: bosh-src/ci/tasks/smoke-deployment.sh
