---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-postgres-10

inputs:
- name: bosh-src
- name: bosh-cli
- name: bosh-agent
- name: integration-tests-parallel-runtime
  optional: true

outputs:
- name: parallel-runtime-log

run:
  path: bosh-src/ci/tasks/test-integration.sh

params:
  RUBY_VERSION:            2.6.3
  DB:                      postgresql
  LOG_LEVEL:               ERROR
  SPEC_PATH:               ~
  SHA2_MODE:               ~
  DB_TLS:                  false
  DEFAULT_UPDATE_VM_STRATEGY: "delete-create"
  NUM_PROCESSES:
