---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main

inputs:
  - name: bosh-src

run:
  path: bosh-src/ci/tasks/test-unit.sh

params:
  RUBY_VERSION: 2.6.3
  DB:           replace-me
  DB_VERSION:   replace-me
