---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main

inputs:
- name: bosh-src
- name: bosh-cli
- name: bosh-agent
- name: integration-tests-parallel-runtime
  optional: true

outputs:
- name: parallel-runtime-log

run:
  path: bosh-src/ci/tasks/test-integration.sh

params:
  RUBY_VERSION:            2.6.3
  DB:                      replace-me
  DB_HOST:                 ~
  DB_PASSWORD:             ~
  DB_USERNAME:             ~
  DB_PORT:                 ~
  DB_NAME:                 ~
  LOG_LEVEL:               ERROR
  SPEC_PATH:               ~
  SHA2_MODE:               ~
  DB_TLS:                  false
  DEFAULT_UPDATE_VM_STRATEGY: "delete-create"
  NUM_PROCESSES:
